POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@wow.com",
  "password": "password"
}


### Get Single User
GET http://localhost:3000/auth/user/3

### Get all Users based on Email
GET http://localhost:3000/auth/user?email=updated@omg.com

### Updates a Single User 
PATCH http://localhost:3000/auth/user
Content-Type: application/json

{
  "id": "1",
  "user": {"email": "testtestesttest@working.com"}
}

### Deletes a Single User
GET  http://localhost:3000/auth/deleteUser?id=2
