### Sign up a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "whyyyy@working.com",
  "password": "pooptastic"
}

### Attempt to sign in user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{ 
  "email": "whyyyy@working.com", 
  "password": "pooptastic"
}

### Get Single User
GET http://localhost:3000/auth/user/3

### Get all Users based on Email
GET http://localhost:3000/auth/user?email=updated@omg.com

### Updates a Single User 
PATCH http://localhost:3000/auth/user/4
Content-Type: application/json

{
  "email": "dog@bitch.com",
  "password": "wuutt"
}

### Deletes a Single User
DELETE  http://localhost:3000/auth/deleteUser/6
